language: ruby
rvm:
  - 1.9
  - 2.2
script: "bundle && bundle exec rake coverage"
gemfile:
  - gemfiles/rails2.gemfile
  - gemfiles/rails4.gemfile
matrix:
  exclude:
    - rvm: 1.9
      gemfile: gemfiles/rails4.gemfile
    - rvm: 2.2
      gemfile: gemfiles/rails2.gemfile
notifications:
  email:
    - support@travellink.com.au
  flowdock: e69dcafad1fea15c6b8c76e9ced965af
