language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
before_install:
  - gem install bundler --version "1.17.3"
  - bundle _1.17.3_ install
script: bundle && bundle exec rake spec
gemfile:
  - gemfiles/rails4.gemfile
  - gemfiles/rails5.gemfile
notifications:
  email:
    - support@travellink.com.au
sudo: false
