language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7
before_install:
  - gem install bundler
script: bundle && bundle exec rspec spec
gemfile:
  - gemfiles/rails5.gemfile
  - gemfiles/rails6.gemfile
notifications:
  email:
    - support@travellink.com.au
sudo: false
cache: bundler
