language: ruby
rvm:
  - 2.2
  - 2.3.0
script: bundle && bundle exec rake spec
gemfile:
  - gemfiles/rails4.gemfile
  - gemfiles/rails5.gemfile
notifications:
  email:
    - support@travellink.com.au
sudo: false
cache: bundler
