---
http_interactions:
- request:
    method: get
    uri: http://test.qt.sealink.com.au:8080/api/resource_categories.json?product_type_ids%5B%5D=1
    body:
      encoding: UTF-8
      string: access_key=<QT_KEY>
    headers:
      Content-Length:
      - '0'
  response:
    status:
      code: 200
      message: 'OK '
    headers:
      P3p:
      - CP="IDC DSP CAO COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
      Content-Type:
      - application/json; charset=utf-8
      Etag:
      - W/"4f53cda18c2baa0c0354bb5f9a3ecbe5"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 55e0d1b4-3b94-4be1-9f57-5c079ac6f894
      X-Runtime:
      - '0.186868'
      Date:
      - Fri, 01 Jan 2016 19:10:52 GMT
      X-Rack-Cache:
      - miss
      Vary:
      - Origin
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Frame-Options:
      - sameorigin
      X-Permitted-Cross-Domain-Policies:
      - none
      X-Xss-Protection:
      - 1; mode=block
      Server:
      - WEBrick/1.3.1 (Ruby/2.2.5/2016-04-26)
      Content-Length:
      - '2'
      Connection:
      - Keep-Alive
      Set-Cookie:
      - _session_id=N2sxVDJ6dzArMDRLWWM0QWMwNS9nT1FYQlM5QlgvS1NBbVVqU1VuNGxFeHZVclREVDFQckRzZGd4TzJNL2hSdzFLRytxTjgreURwc0RLcE1lV2EvNWNMcFZQY0NwTkxtbGl2TnZsVWVRMlE9LS0vc3luMGxXZVRWWEY5TjNxNjF6NmtRPT0%3D--3fc908d694194d82ed0cef8572324484b608ad0f;
        path=/; HttpOnly
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Mon, 19 Mar 2018 21:31:27 GMT
recorded_with: VCR 4.0.0
