---
http_interactions:
- request:
    method: get
    uri: http://0.0.0.0:8080/api/products/6.json?first_travel_date=2016-03-01&passenger_type_numbers[1]=1&date_range[start_date]=2016-03-01&date_range[end_date]=2016-03-02
    body:
      encoding: UTF-8
      string: access_key=<QT_KEY>
    headers:
      Content-Length:
      - '0'
  response:
    status:
      code: 200
      message: 'OK '
    headers:
      P3p:
      - CP="IDC DSP CAO COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
      Content-Type:
      - application/json; charset=utf-8
      X-Ua-Compatible:
      - IE=Edge
      Cache-Control:
      - no-store, must-revalidate, private, max-age=0
      X-Request-Id:
      - d22869d42b05f2f3f1437ae4d96f1b93
      X-Runtime:
      - '1.626568'
      Vary:
      - Origin
      X-Rack-Cache:
      - miss
      X-Miniprofiler-Ids:
      - '["ddvk3xn0wl5x20nkpvba","3n393d46407xjckipoz4","sbzq3sn22o19v6amh4lx","hnsva789t8cmifp64wx3","wmmnukmwie7vr7vj8xqf","2brmax1rs5fwk4fd7n5","dvsmvrl183r0tifnlw46","5o49qsg88hbcsljo43fu","w0wrmi9s9rgua6owkm3z","lxziuvwk5cnyi9wz6zbf"]'
      Server:
      - WEBrick/1.3.1 (Ruby/2.2.3/2015-08-18)
      Date:
      - Mon, 26 Oct 2015 00:18:49 GMT
      Content-Length:
      - '3100'
      Connection:
      - Keep-Alive
      Set-Cookie:
      - __profilin=p%3Dt; path=/
      - __profilin=p%3Dt; path=/
      - __profilin=p%3Dt; path=/
      - _session_id=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJWE4NWI3Y2FmZmYxYTllMzc2ZjE2ZTE1NWI3YmZiNGE1BjsAVEkiCXVzZXIGOwBGaQY%3D--ccba9842ee29fb62055f76a703a934ffe1ecc538;
        path=/; HttpOnly
    body:
      encoding: UTF-8
      string: '{"available":true,"availability_details":{"available":true,"capacity":2,"available_capacity":1,"master_capacity":null,"master_available_capacity":null,"unavailable_type":null},"inventory_type":0,"price":{"_type":"Money","_value":40000},"pricing_details":{"minimum_price":{"_type":"Money","_value":40000},"minimum_price_with_adjustments":{"_type":"Money","_value":20000},"adjustments_to_apply":[{"description":"50%
        Off","gross":{"_type":"Money","_value":-20000},"gross_in_cents":-20000}],"total_adjustments":{"_type":"Money","_value":-20000},"price_per_pax_type":{"":40000},"minimum_price_in_cents":40000,"minimum_price_with_adjustments_in_cents":20000,"total_adjustments_in_cents":-20000,"adjustments_to_apply_in_cents":[-20000],"applied_rules":["Test
        Discount Hilton"]},"reservation_attributes":{"resource_id":6},"resource_class_name_underscore":"accommodation","product_name_underscore":"accommodation","image":{"url":"/assets/default-icon.png","desc":""},"extras":[{"available":true,"availability_details":{"available":true,"capacity":null,"available_capacity":null,"master_capacity":null,"master_available_capacity":null,"unavailable_type":null},"inventory_type":1,"price":{"_type":"Money","_value":6000},"pricing_details":{"minimum_price":{"_type":"Money","_value":6000},"minimum_price_with_adjustments":{"_type":"Money","_value":3000},"adjustments_to_apply":[{"description":"50%
        Off","gross":{"_type":"Money","_value":-3000},"gross_in_cents":-3000}],"total_adjustments":{"_type":"Money","_value":-3000},"price_per_pax_type":{"1":6000},"minimum_price_in_cents":6000,"minimum_price_with_adjustments_in_cents":3000,"total_adjustments_in_cents":-3000,"adjustments_to_apply_in_cents":[-3000],"applied_rules":["QBE
        Get Me"]},"reservation_attributes":{"resource_id":3},"resource_class_name_underscore":"insurance","product_name_underscore":"travel_insurance","image":{"url":"/assets/default-icon.png","desc":""},"extras":[],"selection_name":"QBE
        Travel Insurance - Policy E","description":"QBE Travel Insurance - Policy
        E","error_message":null},{"available":true,"availability_details":{"available":true,"capacity":null,"available_capacity":null,"master_capacity":null,"master_available_capacity":null,"unavailable_type":null},"inventory_type":1,"price":{"_type":"Money","_value":6000},"pricing_details":{"minimum_price":{"_type":"Money","_value":6000},"minimum_price_with_adjustments":{"_type":"Money","_value":6000},"adjustments_to_apply":[],"total_adjustments":{"_type":"Money","_value":0},"price_per_pax_type":{"1":6000},"minimum_price_in_cents":6000,"minimum_price_with_adjustments_in_cents":6000,"total_adjustments_in_cents":0,"adjustments_to_apply_in_cents":[],"applied_rules":[]},"reservation_attributes":{"resource_id":4},"resource_class_name_underscore":"insurance","product_name_underscore":"travel_insurance","image":{"url":"/assets/default-icon.png","desc":""},"extras":[],"selection_name":"Travel
        Insurance - Declined","description":"Travel Insurance - Declined","error_message":null}],"selection_name":"Executive
        Room","description":"Hilton Hotel - Executive Room","error_message":null}'
    http_version: 
  recorded_at: Mon, 26 Oct 2015 00:18:49 GMT
recorded_with: VCR 2.9.3
