---
http_interactions:
- request:
    method: get
    uri: http://test.qt.sealink.com.au:8080/api/resource_categories.json?product_type_ids%5B%5D=1
    body:
      encoding: UTF-8
      string: access_key=<QT_KEY>
    headers:
      Content-Length:
      - '0'
  response:
    status:
      code: 200
      message: 'OK '
    headers:
      P3p:
      - CP="IDC DSP CAO COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
      Content-Type:
      - application/json; charset=utf-8
      Etag:
      - W/"4f53cda18c2baa0c0354bb5f9a3ecbe5"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 6551d2a8-5997-487d-9d11-d297a5a8349b
      X-Runtime:
      - '0.130342'
      Date:
      - Fri, 01 Jan 2016 02:32:28 GMT
      X-Rack-Cache:
      - miss
      Vary:
      - Origin
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Frame-Options:
      - sameorigin
      X-Permitted-Cross-Domain-Policies:
      - none
      X-Xss-Protection:
      - 1; mode=block
      Server:
      - WEBrick/1.3.1 (Ruby/2.2.5/2016-04-26)
      Content-Length:
      - '2'
      Connection:
      - Keep-Alive
      Set-Cookie:
      - _session_id=ZUJPRHB6cEVCU0M1QmhIdU54WExkdlVZcUowMEtpN1VnenpBck9JSkFPVmRsUE9kWmZ0dnpvR3hPUXl0U0NxSEp4dklDWXdBZ0RiZEUweFZBUEN3SVlrQTRhZUIxVnc4TXltQlR4d1RjNDQ9LS1Zekk0TjdFdkx0TnFZTUdQS2tIR0JRPT0%3D--6fbdde6e8a269b3617d8ecfad647ce438127e94d;
        path=/; HttpOnly
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Wed, 21 Mar 2018 04:40:35 GMT
recorded_with: VCR 4.0.0
