---
http_interactions:
- request:
    method: get
    uri: http://test.qt.sealink.com.au:8080/product_types/1/routes.json
    body:
      encoding: UTF-8
      string: access_key=<QT_KEY>
    headers:
      Content-Length:
      - '0'
  response:
    status:
      code: 200
      message: 'OK '
    headers:
      P3p:
      - CP="IDC DSP CAO COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
      Content-Type:
      - application/json; charset=utf-8
      Etag:
      - W/"081240e8bd7d85593c37e53d9a7fe909"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 8420fa5a-7432-4aa2-acda-abc75386e1af
      X-Runtime:
      - '0.150295'
      Date:
      - Fri, 01 Jan 2016 02:38:43 GMT
      X-Rack-Cache:
      - miss
      Vary:
      - Origin
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Frame-Options:
      - sameorigin
      X-Permitted-Cross-Domain-Policies:
      - none
      X-Xss-Protection:
      - 1; mode=block
      Server:
      - WEBrick/1.3.1 (Ruby/2.2.5/2016-04-26)
      Content-Length:
      - '973'
      Connection:
      - Keep-Alive
      Set-Cookie:
      - _session_id=RFNCSVA5ZWV2OEZuZmc0T1JBL0xMWnMxMU9HS0FMbVBFNTUrZTdWMWpwbitJYUZnSG5nUm9KZHkzcVhrSVRuTEpPendJdXpQa0tqZXdBRlVNaHdGMVluNWY1VVBoK1p0eFJSSy9tVDBkcVk9LS1jaGpjaDBKbStKZVh5bkQ3Mmp2eVRRPT0%3D--b58bcd8833551019b9859db5fbc0aabc2fe21e9b;
        path=/; HttpOnly
    body:
      encoding: UTF-8
      string: '[{"id":1,"product_type_id":1,"reverse_id":2,"position":1,"created_at":null,"updated_at":null,"name":"To
        Kangaroo Island","path":"Cape Jervis to Penneshaw","route_stops":[{"id":1,"inventory_controlled":true,"route_id":1,"position":1,"created_at":null,"updated_at":null,"stop_id":1,"name":"Cape
        Jervis","code":"CPJ","address":""},{"id":2,"inventory_controlled":true,"route_id":1,"position":2,"created_at":null,"updated_at":null,"stop_id":2,"name":"Penneshaw","code":"PEN","address":""}]},{"id":2,"product_type_id":1,"reverse_id":1,"position":2,"created_at":null,"updated_at":null,"name":"From
        Kangaroo Island","path":"Penneshaw to Cape Jervis","route_stops":[{"id":3,"inventory_controlled":true,"route_id":2,"position":1,"created_at":null,"updated_at":null,"stop_id":2,"name":"Penneshaw","code":"PEN","address":""},{"id":4,"inventory_controlled":true,"route_id":2,"position":2,"created_at":null,"updated_at":null,"stop_id":1,"name":"Cape
        Jervis","code":"CPJ","address":""}]}]'
    http_version: 
  recorded_at: Tue, 20 Mar 2018 04:32:05 GMT
recorded_with: VCR 4.0.0
