---
http_interactions:
- request:
    method: get
    uri: http://test.qt.sealink.com.au:8080/api/resource_categories.json?product_type_ids%5B%5D=1
    body:
      encoding: UTF-8
      string: access_key=<QT_KEY>
    headers:
      Content-Length:
      - '0'
  response:
    status:
      code: 200
      message: 'OK '
    headers:
      P3p:
      - CP="IDC DSP CAO COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
      Content-Type:
      - application/json; charset=utf-8
      Etag:
      - W/"4f53cda18c2baa0c0354bb5f9a3ecbe5"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 243e7df5-cf2e-4887-96be-3e583f783054
      X-Runtime:
      - '0.136764'
      Date:
      - Fri, 01 Jan 2016 02:38:43 GMT
      X-Rack-Cache:
      - miss
      Vary:
      - Origin
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Frame-Options:
      - sameorigin
      X-Permitted-Cross-Domain-Policies:
      - none
      X-Xss-Protection:
      - 1; mode=block
      Server:
      - WEBrick/1.3.1 (Ruby/2.2.5/2016-04-26)
      Content-Length:
      - '2'
      Connection:
      - Keep-Alive
      Set-Cookie:
      - _session_id=SFJsUi9vUGpiL0kzbVRnVDdIVWhSZHE5dVpOYnRESnQzUng4bDBUTFBNb002TFZRWTBkdVBOSm9ZbGx5S3N5ak9mc0ZPZ0RBTlgyMVlWTXRNR3l3Q205VlR3dG1Qd05rek5kVkYxMytIQzQ9LS1pcU81WEVCRXJBdk5SWEFlQVVqd0J3PT0%3D--534f5015f5150e7ad3a0a6f2d1664fdbe7f9d334;
        path=/; HttpOnly
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Tue, 20 Mar 2018 04:32:05 GMT
recorded_with: VCR 4.0.0
