---
http_interactions:
- request:
    method: get
    uri: http://test.qt.sealink.com.au:8080/api/products/6.json?date_range%5Bend_date%5D=2016-03-02&date_range%5Bstart_date%5D=2016-03-01&first_travel_date=2016-03-01&passenger_type_numbers%5B%5D=1&rack_price_requested=true
    body:
      encoding: UTF-8
      string: access_key=<QT_KEY>
    headers:
      Content-Length:
      - '0'
  response:
    status:
      code: 200
      message: 'OK '
    headers:
      P3p:
      - CP="IDC DSP CAO COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
      Content-Type:
      - application/json; charset=utf-8
      Etag:
      - W/"8906c6b376c4d36d43d4b122ac73d367"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - deb239ca-ed6b-4770-876e-ad2d095fb643
      X-Runtime:
      - '0.833342'
      Date:
      - Fri, 01 Jan 2016 02:32:26 GMT
      X-Rack-Cache:
      - miss
      Vary:
      - Origin
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Frame-Options:
      - sameorigin
      X-Permitted-Cross-Domain-Policies:
      - none
      X-Xss-Protection:
      - 1; mode=block
      Server:
      - WEBrick/1.3.1 (Ruby/2.2.5/2016-04-26)
      Content-Length:
      - '2689'
      Connection:
      - Keep-Alive
      Set-Cookie:
      - _session_id=VkorVXAySFdWaVlaQ1hOTmlCb1hJZmxrcFNLUU44Q2E1aHNCMmwrSjlENjZFeWJIeXpYRTdzMjBYRnFGZ241NThoSXpvZk01Yi92UUFSRTFGYVFTREo1SVhLUjdJeEg1QXRjTnhNcFJSckk9LS02cHN6cFVySTJnaHp0bHUzOU0yc3hBPT0%3D--861222141f7892ee33ae2f1d1fe820a44b4e61db;
        path=/; HttpOnly
    body:
      encoding: UTF-8
      string: '{"available":true,"availability_details":{"available":true,"capacity":2,"available_capacity":null,"master_capacity":null,"master_available_capacity":null,"unavailable_type":null},"inventory_type":0,"pricing_details":{"price_per_pax_type":{"":40000},"minimum_price_in_cents":40000,"minimum_price_with_adjustments_in_cents":20000,"total_adjustments_in_cents":-20000,"applied_rules":["Test
        Discount Hilton"]},"pricing_details_for_rack_rate":{"price_per_pax_type":{"":40000},"minimum_price_in_cents":40000,"minimum_price_with_adjustments_in_cents":40000,"total_adjustments_in_cents":0,"applied_rules":[]},"reservation_attributes":{"resource_id":6},"resource_class_name_underscore":"accommodation","product_name_underscore":"accommodation","image":{"url":"/assets/default-icon.png","desc":""},"extras":[{"available":true,"availability_details":{"available":true,"capacity":1,"available_capacity":null,"master_capacity":null,"master_available_capacity":null,"unavailable_type":null},"inventory_type":1,"pricing_details":{"price_per_pax_type":{"1":6000},"minimum_price_in_cents":6000,"minimum_price_with_adjustments_in_cents":3000,"total_adjustments_in_cents":-3000,"applied_rules":["QBE
        Get Me"]},"pricing_details_for_rack_rate":{"price_per_pax_type":{"1":6000},"minimum_price_in_cents":6000,"minimum_price_with_adjustments_in_cents":6000,"total_adjustments_in_cents":0,"applied_rules":[]},"reservation_attributes":{"resource_id":3},"resource_class_name_underscore":"insurance","product_name_underscore":"travel_insurance","image":{"url":"/assets/default-icon.png","desc":""},"extras":[],"selection_name":"QBE
        Travel Insurance - Policy E","description":"QBE Travel Insurance - Policy
        E","error_message":null},{"available":true,"availability_details":{"available":true,"capacity":null,"available_capacity":null,"master_capacity":null,"master_available_capacity":null,"unavailable_type":null},"inventory_type":1,"pricing_details":{"price_per_pax_type":{"1":6000},"minimum_price_in_cents":6000,"minimum_price_with_adjustments_in_cents":6000,"total_adjustments_in_cents":0,"applied_rules":[]},"pricing_details_for_rack_rate":{"price_per_pax_type":{"1":6000},"minimum_price_in_cents":6000,"minimum_price_with_adjustments_in_cents":6000,"total_adjustments_in_cents":0,"applied_rules":[]},"reservation_attributes":{"resource_id":4},"resource_class_name_underscore":"insurance","product_name_underscore":"travel_insurance","image":{"url":"/assets/default-icon.png","desc":""},"extras":[],"selection_name":"Travel
        Insurance - Declined","description":"Travel Insurance - Declined","error_message":null}],"selection_name":"Executive
        Room","description":"Hilton Hotel - Executive Room","error_message":null}'
    http_version: 
  recorded_at: Wed, 21 Mar 2018 04:40:33 GMT
recorded_with: VCR 4.0.0
