---
http_interactions:
- request:
    method: get
    uri: http://test.qt.sealink.com.au:8080/api/resource_categories.json?product_type_ids%5B%5D=5
    body:
      encoding: UTF-8
      string: access_key=<QT_KEY>
    headers:
      Content-Length:
      - '0'
  response:
    status:
      code: 200
      message: 'OK '
    headers:
      P3p:
      - CP="IDC DSP CAO COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
      Content-Type:
      - application/json; charset=utf-8
      Etag:
      - W/"3b463d79f48c515bd0ed3e6b755d1d4b"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 6c30923c-7795-4fab-9226-f786afed9bd0
      X-Runtime:
      - '0.147175'
      Date:
      - Fri, 01 Jan 2016 19:10:52 GMT
      X-Rack-Cache:
      - miss
      Vary:
      - Origin
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Frame-Options:
      - sameorigin
      X-Permitted-Cross-Domain-Policies:
      - none
      X-Xss-Protection:
      - 1; mode=block
      Server:
      - WEBrick/1.3.1 (Ruby/2.2.5/2016-04-26)
      Content-Length:
      - '240'
      Connection:
      - Keep-Alive
      Set-Cookie:
      - _session_id=eUgydzNGUUZVN1hEaW5DbjhCemZwMkVxVCt2RXM1S0RXRXFLc2VpeDQrdnhXZUxsRC8xbTV2Y0t5MHVzMnY5YUF1Z3JZT24xV3NnS1ZOOWYxR0NKRGYzNjF1cEdZRUhlSTJWWVhVNmxRak09LS1ZV1ZMVVh6cEE1OFo1ZWx0UEVZV2dnPT0%3D--557662dd573608ee8bf92473f9fdd5e346765aef;
        path=/; HttpOnly
    body:
      encoding: UTF-8
      string: '[{"id":1,"name":"Common","description":null,"product_type_id":5,"created_at":null,"updated_at":null,"position":null},{"id":2,"name":"Multiple
        Trip","description":null,"product_type_id":5,"created_at":null,"updated_at":null,"position":null}]'
    http_version: 
  recorded_at: Mon, 19 Mar 2018 21:31:27 GMT
recorded_with: VCR 4.0.0
