---
http_interactions:
- request:
    method: get
    uri: http://test.qt.sealink.com.au:8080/api/resource_categories.json?product_type_ids%5B%5D=5
    body:
      encoding: UTF-8
      string: access_key=<QT_KEY>
    headers:
      Content-Length:
      - '0'
  response:
    status:
      code: 200
      message: 'OK '
    headers:
      P3p:
      - CP="IDC DSP CAO COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
      Content-Type:
      - application/json; charset=utf-8
      Etag:
      - W/"3b463d79f48c515bd0ed3e6b755d1d4b"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 7b5c8877-bbdd-4ae6-9c02-e66f18d5a363
      X-Runtime:
      - '0.140122'
      Date:
      - Fri, 01 Jan 2016 02:38:43 GMT
      X-Rack-Cache:
      - miss
      Vary:
      - Origin
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Frame-Options:
      - sameorigin
      X-Permitted-Cross-Domain-Policies:
      - none
      X-Xss-Protection:
      - 1; mode=block
      Server:
      - WEBrick/1.3.1 (Ruby/2.2.5/2016-04-26)
      Content-Length:
      - '240'
      Connection:
      - Keep-Alive
      Set-Cookie:
      - _session_id=ZmJMdjl4YStxejRHcUxSaE53NUs5eXJtTTNJK3FrYytyaDc0Y3FnNGNXQXBXU2RvVTJRa3p4eXp2cXRZWGQ3N2s1ajlTRGpCSjFaZjVHQS9GTE9FVUd3UjNKRElUSTFoMDlETHdrR1RWUEE9LS1scEJVci85RGxXZTl3YitaQmlZRURnPT0%3D--72685f2e140fa173ccf28403d479cf45ade844ae;
        path=/; HttpOnly
    body:
      encoding: UTF-8
      string: '[{"id":1,"name":"Common","description":null,"product_type_id":5,"created_at":null,"updated_at":null,"position":null},{"id":2,"name":"Multiple
        Trip","description":null,"product_type_id":5,"created_at":null,"updated_at":null,"position":null}]'
    http_version: 
  recorded_at: Tue, 20 Mar 2018 04:32:05 GMT
recorded_with: VCR 4.0.0
