---
http_interactions:
- request:
    method: get
    uri: http://test.qt.sealink.com.au:8080/api/resource_categories.json?product_type_ids%5B%5D=1
    body:
      encoding: UTF-8
      string: access_key=<QT_KEY>
    headers:
      Content-Length:
      - '0'
  response:
    status:
      code: 200
      message: 'OK '
    headers:
      P3p:
      - CP="IDC DSP CAO COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
      Content-Type:
      - application/json; charset=utf-8
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - abeeb7c1da610a4ec0669b1af29f1de1
      X-Runtime:
      - '0.083924'
      Vary:
      - Origin
      Date:
      - Fri, 01 Jan 2016 02:32:36 GMT
      X-Rack-Cache:
      - miss
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Frame-Options:
      - sameorigin
      X-Permitted-Cross-Domain-Policies:
      - none
      X-Xss-Protection:
      - 1; mode=block
      Server:
      - WEBrick/1.3.1 (Ruby/2.2.5/2016-04-26)
      Content-Length:
      - '2'
      Connection:
      - Keep-Alive
      Set-Cookie:
      - _quick_travel_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJTQ4NDQwMGJkNmNkNzM4MmUwYjlhOWFhYzQ4NmNhZDliBjsAVEkiCXVzZXIGOwBGaQY%3D--4c9774af3f338d0eb51870362aa2d15e0fc500c3;
        path=/; HttpOnly
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Fri, 28 Oct 2016 05:28:13 GMT
recorded_with: VCR 3.0.3
