---
http_interactions:
- request:
    method: get
    uri: http://test.qt.sealink.com.au:8080/product_types/1/routes.json
    body:
      encoding: UTF-8
      string: access_key=<QT_KEY>
    headers:
      Content-Length:
      - '0'
  response:
    status:
      code: 200
      message: 'OK '
    headers:
      P3p:
      - CP="IDC DSP CAO COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
      Content-Type:
      - application/json; charset=utf-8
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Etag:
      - '"569a4ede07372a75b7f3e16dc376e665"'
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 891ae78decad381b6c518175b6f12bfd
      X-Runtime:
      - '0.118721'
      Vary:
      - Origin
      Date:
      - Fri, 01 Jan 2016 02:32:36 GMT
      X-Rack-Cache:
      - miss
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Frame-Options:
      - sameorigin
      X-Permitted-Cross-Domain-Policies:
      - none
      X-Xss-Protection:
      - 1; mode=block
      Server:
      - WEBrick/1.3.1 (Ruby/2.2.5/2016-04-26)
      Content-Length:
      - '1249'
      Connection:
      - Keep-Alive
      Set-Cookie:
      - _quick_travel_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJWFmMTY0YWM3Njg2MzExMDJhMjk3ZDY1MjkzMDc5MGM0BjsAVEkiCXVzZXIGOwBGaQY%3D--783ac9119bad9c2ce1800a12fc537268eddb4d0d;
        path=/; HttpOnly
    body:
      encoding: UTF-8
      string: '[{"id":1,"product_type_id":1,"reverse_id":2,"position":1,"created_at":"2013-03-01T00:01:37+10:30","updated_at":"2013-03-01T00:06:45+10:30","name":"To
        Kangaroo Island","path":"Cape Jervis to Penneshaw","route_stops":[{"id":1,"inventory_controlled":true,"route_id":1,"position":1,"created_at":"2013-03-01T00:01:37+10:30","updated_at":"2013-03-01T00:01:37+10:30","stop_id":1,"name":"Cape
        Jervis","code":"CPJ","address":""},{"id":2,"inventory_controlled":true,"route_id":1,"position":2,"created_at":"2013-03-01T00:01:37+10:30","updated_at":"2013-03-01T00:01:37+10:30","stop_id":2,"name":"Penneshaw","code":"PEN","address":""}]},{"id":2,"product_type_id":1,"reverse_id":1,"position":2,"created_at":"2013-03-01T00:02:06+10:30","updated_at":"2013-03-01T00:06:38+10:30","name":"From
        Kangaroo Island","path":"Penneshaw to Cape Jervis","route_stops":[{"id":3,"inventory_controlled":true,"route_id":2,"position":1,"created_at":"2013-03-01T00:02:06+10:30","updated_at":"2013-03-01T00:02:06+10:30","stop_id":2,"name":"Penneshaw","code":"PEN","address":""},{"id":4,"inventory_controlled":true,"route_id":2,"position":2,"created_at":"2013-03-01T00:02:06+10:30","updated_at":"2013-03-01T00:02:06+10:30","stop_id":1,"name":"Cape
        Jervis","code":"CPJ","address":""}]}]'
    http_version: 
  recorded_at: Fri, 28 Oct 2016 05:28:13 GMT
recorded_with: VCR 3.0.3
