---
http_interactions:
- request:
    method: get
    uri: http://test.qt.sealink.com.au:8080/api/resource_categories.json?product_type_ids%5B%5D=5
    body:
      encoding: UTF-8
      string: access_key=<QT_KEY>
    headers:
      Content-Length:
      - '0'
  response:
    status:
      code: 200
      message: 'OK '
    headers:
      P3p:
      - CP="IDC DSP CAO COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
      Content-Type:
      - application/json; charset=utf-8
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Etag:
      - '"d1fd940d0166dbb4832b5f5171b67a60"'
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - f6cd11cba56885f3e309a07dc4fb526f
      X-Runtime:
      - '0.069853'
      Vary:
      - Origin
      Date:
      - Fri, 01 Jan 2016 02:32:36 GMT
      X-Rack-Cache:
      - miss
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Frame-Options:
      - sameorigin
      X-Permitted-Cross-Domain-Policies:
      - none
      X-Xss-Protection:
      - 1; mode=block
      Server:
      - WEBrick/1.3.1 (Ruby/2.2.5/2016-04-26)
      Content-Length:
      - '328'
      Connection:
      - Keep-Alive
      Set-Cookie:
      - _quick_travel_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJTZiZWEwOWMwYmYzMzQ4MDhjYjViZWIyN2FlMDkwZDNjBjsAVEkiCXVzZXIGOwBGaQY%3D--ce1756095e1dcab88d9b48fe05070de5ca0868cc;
        path=/; HttpOnly
    body:
      encoding: UTF-8
      string: '[{"created_at":"2015-08-25T14:14:25+09:30","description":"","id":1,"name":"Common","position":null,"product_type_id":5,"updated_at":"2015-08-25T14:14:25+09:30"},{"created_at":"2015-08-25T14:14:50+09:30","description":"","id":2,"name":"Multiple
        Trip","position":null,"product_type_id":5,"updated_at":"2015-08-25T14:14:50+09:30"}]'
    http_version: 
  recorded_at: Fri, 28 Oct 2016 05:28:13 GMT
recorded_with: VCR 3.0.3
