---
http_interactions:
- request:
    method: get
    uri: http://test.qt.sealink.com.au:8080/api/products/6.json?date_range%5Bend_date%5D=2016-03-02&date_range%5Bstart_date%5D=2016-03-01&first_travel_date=2016-03-01&passenger_type_numbers%5B%5D=1
    body:
      encoding: UTF-8
      string: access_key=<QT_KEY>
    headers:
      Content-Length:
      - '0'
  response:
    status:
      code: 200
      message: 'OK '
    headers:
      P3p:
      - CP="IDC DSP CAO COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
      Content-Type:
      - application/json; charset=utf-8
      Etag:
      - W/"1728c9d08e89efda28c50f0378433dc7"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 8a12b94e-9e8a-4532-8a70-ca06fb69ec93
      X-Runtime:
      - '0.657396'
      Date:
      - Fri, 01 Jan 2016 02:38:40 GMT
      X-Rack-Cache:
      - miss
      Vary:
      - Origin
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Frame-Options:
      - sameorigin
      X-Permitted-Cross-Domain-Policies:
      - none
      X-Xss-Protection:
      - 1; mode=block
      Server:
      - WEBrick/1.3.1 (Ruby/2.2.5/2016-04-26)
      Content-Length:
      - '2108'
      Connection:
      - Keep-Alive
      Set-Cookie:
      - _session_id=RHlJV1dnMC90TCtaNXZWMEVIV2h0TjB5dlg2Uy9PRTZJUXBDUGRTd09mVXo5VkVTK2FGbnJTeG5qcU1wK1lROFd5R0Zkc0VNVDJTTldyQjdaSFdydlRMdjN1T1lCTlQrQlZFQjhVUDlZTlk9LS1XcjBoeFFXRVh3T29vSTdoRGxNekVRPT0%3D--f2e3ee23e5cbd237fd446dc4e699d31b34560878;
        path=/; HttpOnly
    body:
      encoding: UTF-8
      string: '{"available":true,"availability_details":{"available":true,"capacity":2,"available_capacity":null,"master_capacity":null,"master_available_capacity":null,"unavailable_type":null},"inventory_type":0,"pricing_details":{"price_per_pax_type":{"":40000},"minimum_price_in_cents":40000,"minimum_price_with_adjustments_in_cents":20000,"total_adjustments_in_cents":-20000,"applied_rules":["Test
        Discount Hilton"]},"reservation_attributes":{"resource_id":6},"resource_class_name_underscore":"accommodation","product_name_underscore":"accommodation","image":{"url":"/assets/default-icon.png","desc":""},"extras":[{"available":true,"availability_details":{"available":true,"capacity":1,"available_capacity":null,"master_capacity":null,"master_available_capacity":null,"unavailable_type":null},"inventory_type":1,"pricing_details":{"price_per_pax_type":{"1":6000},"minimum_price_in_cents":6000,"minimum_price_with_adjustments_in_cents":3000,"total_adjustments_in_cents":-3000,"applied_rules":["QBE
        Get Me"]},"reservation_attributes":{"resource_id":3},"resource_class_name_underscore":"insurance","product_name_underscore":"travel_insurance","image":{"url":"/assets/default-icon.png","desc":""},"extras":[],"selection_name":"QBE
        Travel Insurance - Policy E","description":"QBE Travel Insurance - Policy
        E","error_message":null},{"available":true,"availability_details":{"available":true,"capacity":null,"available_capacity":null,"master_capacity":null,"master_available_capacity":null,"unavailable_type":null},"inventory_type":1,"pricing_details":{"price_per_pax_type":{"1":6000},"minimum_price_in_cents":6000,"minimum_price_with_adjustments_in_cents":6000,"total_adjustments_in_cents":0,"applied_rules":[]},"reservation_attributes":{"resource_id":4},"resource_class_name_underscore":"insurance","product_name_underscore":"travel_insurance","image":{"url":"/assets/default-icon.png","desc":""},"extras":[],"selection_name":"Travel
        Insurance - Declined","description":"Travel Insurance - Declined","error_message":null}],"selection_name":"Executive
        Room","description":"Hilton Hotel - Executive Room","error_message":null}'
    http_version: 
  recorded_at: Tue, 20 Mar 2018 04:32:02 GMT
recorded_with: VCR 4.0.0
