---
http_interactions:
- request:
    method: get
    uri: http://test.qt.sealink.com.au:8080/product_types/1/routes.json
    body:
      encoding: UTF-8
      string: access_key=<QT_KEY>
    headers:
      Content-Length:
      - '0'
  response:
    status:
      code: 200
      message: 'OK '
    headers:
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - '1'
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      P3p:
      - CP="IDC DSP CAO COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
      Content-Type:
      - application/json; charset=utf-8
      X-Ua-Compatible:
      - IE=Edge
      Etag:
      - '"2d8100d816a9ad65d0a2e3e9191fed41"'
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 0e12f505a73e6b6edca1c8ca37b75f8d
      X-Runtime:
      - '0.072749'
      Vary:
      - Origin
      Date:
      - Mon, 11 Apr 2016 02:05:37 GMT
      X-Rack-Cache:
      - miss
      Server:
      - WEBrick/1.3.1 (Ruby/2.2.4/2015-12-16)
      Content-Length:
      - '1249'
      Connection:
      - Keep-Alive
      Set-Cookie:
      - _session_id=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJTFkZjYzYTNjOGIyMzcyMTZlYTFjNmVjOTc5YzAxYzRkBjsAVEkiCXVzZXIGOwBGaQY%3D--0a0b632fa75e54e9bc37d292ab8bc2a17704536f;
        path=/; HttpOnly
    body:
      encoding: UTF-8
      string: '[{"id":1,"product_type_id":1,"reverse_id":2,"position":1,"created_at":"2013-03-01T00:01:37+10:30","updated_at":"2013-03-01T00:06:45+10:30","name":"To
        Kangaroo Island","path":"Cape Jervis to Penneshaw","route_stops":[{"id":1,"name":"Cape
        Jervis","address":"","inventory_controlled":true,"route_id":1,"position":1,"created_at":"2013-03-01T00:01:37+10:30","updated_at":"2013-03-01T00:01:37+10:30","code":"CPJ","stop_id":1},{"id":2,"name":"Penneshaw","address":"","inventory_controlled":true,"route_id":1,"position":2,"created_at":"2013-03-01T00:01:37+10:30","updated_at":"2013-03-01T00:01:37+10:30","code":"PEN","stop_id":2}]},{"id":2,"product_type_id":1,"reverse_id":1,"position":2,"created_at":"2013-03-01T00:02:06+10:30","updated_at":"2013-03-01T00:06:38+10:30","name":"From
        Kangaroo Island","path":"Penneshaw to Cape Jervis","route_stops":[{"id":3,"name":"Penneshaw","address":"","inventory_controlled":true,"route_id":2,"position":1,"created_at":"2013-03-01T00:02:06+10:30","updated_at":"2013-03-01T00:02:06+10:30","code":"PEN","stop_id":2},{"id":4,"name":"Cape
        Jervis","address":"","inventory_controlled":true,"route_id":2,"position":2,"created_at":"2013-03-01T00:02:06+10:30","updated_at":"2013-03-01T00:02:06+10:30","code":"CPJ","stop_id":1}]}]'
    http_version: 
  recorded_at: Mon, 11 Apr 2016 02:05:37 GMT
recorded_with: VCR 3.0.1
