---
http_interactions:
- request:
    method: get
    uri: http://test.qt.sealink.com.au:8080/api/settings/basic.json
    body:
      encoding: UTF-8
      string: access_key=<QT_KEY>
    headers:
      Content-Length:
      - '0'
  response:
    status:
      code: 200
      message: 'OK '
    headers:
      P3p:
      - CP="IDC DSP CAO COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
      Content-Type:
      - application/json; charset=utf-8
      Etag:
      - W/"fa3cf293c3f4a0785f054bee171056d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 892f2cd4-3ed7-4f4f-bbc5-c82668ce1d2b
      X-Runtime:
      - '0.212347'
      Date:
      - Fri, 01 Jan 2016 19:11:02 GMT
      X-Rack-Cache:
      - miss
      Vary:
      - Origin
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Frame-Options:
      - sameorigin
      X-Permitted-Cross-Domain-Policies:
      - none
      X-Xss-Protection:
      - 1; mode=block
      Server:
      - WEBrick/1.3.1 (Ruby/2.2.5/2016-04-26)
      Content-Length:
      - '195'
      Connection:
      - Keep-Alive
      Set-Cookie:
      - _session_id=UTRhOUNDWTRMOWdHTWY1VkhaUVBGV3Q2QkhZNWk5NEx2cjZMR25GbDF4aE5mVmE5RTVSNXY5bkcvQ2RrYWV6MWhiWVFrZUcrVXQ4Z2d4RWdRZWw0Wnkxa0tXNVZKZTN2MjFkdGo1NDZrU289LS1sSmpDcFhweCsvRFQ5SmJRZUppTnJ3PT0%3D--da5ba71817dd4fd240ce87a868c1f2ff30c93694;
        path=/; HttpOnly
    body:
      encoding: UTF-8
      string: '{"vehicle_optional_fields":["weight","registration"],"default_passenger_type_id":1,"time_zone":"Australia/Adelaide","ob_num_pax_requiring_details":"none","person_titles":["Mr","Mrs","Ms","Miss"]}'
    http_version: 
  recorded_at: Mon, 19 Mar 2018 21:31:37 GMT
recorded_with: VCR 4.0.0
