---
http_interactions:
- request:
    method: get
    uri: http://test.qt.sealink.com.au:8080/api/settings/basic.json
    body:
      encoding: UTF-8
      string: access_key=<QT_KEY>
    headers:
      Content-Length:
      - '0'
  response:
    status:
      code: 200
      message: 'OK '
    headers:
      P3p:
      - CP="IDC DSP CAO COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
      Content-Type:
      - application/json; charset=utf-8
      Etag:
      - W/"fa3cf293c3f4a0785f054bee171056d2"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 7e9c3b8d-010b-4f52-894c-979a37c485d6
      X-Runtime:
      - '0.177874'
      Date:
      - Fri, 01 Jan 2016 20:48:46 GMT
      X-Rack-Cache:
      - miss
      Vary:
      - Origin
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Frame-Options:
      - sameorigin
      X-Permitted-Cross-Domain-Policies:
      - none
      X-Xss-Protection:
      - 1; mode=block
      Server:
      - WEBrick/1.3.1 (Ruby/2.2.5/2016-04-26)
      Content-Length:
      - '195'
      Connection:
      - Keep-Alive
      Set-Cookie:
      - _session_id=NjlTajBNRWhaT2hRVmVzajY1ZHFsR1l5QnpNT1lqd2JzVjJGOGlVTGpYakVFS3hLS1dSUEo3WDNhcUJldjk1aUdXRm1uRUpleXVtVnRDRE1rakhLYW5kaEVaUjRSRmlHRTkzUnlpSkI3QjQ9LS1qKzNYaWhZK1NnK3d3dUNYQzh3eW1BPT0%3D--5695a7f5309c1efed9edede3c4ccf3349bf2b8cd;
        path=/; HttpOnly
    body:
      encoding: UTF-8
      string: '{"vehicle_optional_fields":["weight","registration"],"default_passenger_type_id":1,"time_zone":"Australia/Adelaide","ob_num_pax_requiring_details":"none","person_titles":["Mr","Mrs","Ms","Miss"]}'
    http_version: 
  recorded_at: Tue, 06 Feb 2018 20:49:49 GMT
recorded_with: VCR 3.0.3
